### ISSUE TITLE
The sample case does not work

### ISSUE THREAD

**Issue by Eureka10shen** [n-gao/pesnet#1]
I'm running the sample case
```bash
python train.py with configs/systems/h2.yaml print_progress=True
```
but there came the errors
```bash
2023-04-03 17:17:27 (ERROR): Traceback (most recent call last):
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/seml_logger/__init__.py", line 48, in func
    logger = Logger(
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/seml_logger/logger.py", line 64, in __init__
    self.aim_run = aim.Run(self.aim_repo, self.experiment)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 70, in wrapper
    _SafeModeConfig.exception_callback(e, func)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 47, in reraise_exception
    raise e
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 68, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/sacred/run.py", line 429, in _final_call
    getattr(observer, method)(**kwargs)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/seml/observers.py", line 410, in failed_event
    requests.post(self.webhook_url, data=json.dumps(data), headers=headers)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'YOUR_WEBHOOK': No scheme supplied. Perhaps you meant https://YOUR_WEBHOOK?

Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/seml_logger/__init__.py", line 48, in func
    logger = Logger(
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/seml_logger/logger.py", line 64, in __init__
    self.aim_run = aim.Run(self.aim_repo, self.experiment)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 70, in wrapper
    _SafeModeConfig.exception_callback(e, func)
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 47, in reraise_exception
    raise e
  File "/home/kf/anaconda3/envs/py38_aux/lib/python3.8/site-packages/aim/ext/exception_resistant.py", line 68, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```
It seems that the errors came from the ```seml``` package.
How can we solve it ?

**Comment by n-gao** [comment]
Thanks a lot for pointing this out! This has been fixed in https://github.com/n-gao/seml_logger/commit/5eb5f19d1694d858af0c727291284e16a8d190e1. Please uninstall `seml_logger` and reinstall it with 
`pip install git+https://github.com/n-gao/seml_logger.git` and tell me whether that resolved the issue for you!

Edit: To avoid such situations, I added some specifications for important packages in 516bfde156378482d4548eb8185bd36106d887b5.

**Comment by Eureka10shen** [comment]
The issue can be resolved. Thank you!!!
